# Generated by Django 4.2.4 on 2026-07-03 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('razon_social', models.CharField(blank=True, max_length=150)),
            ],
            options={
                'verbose_name_plural': 'empresas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Feriado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'feriados',
                'ordering': ['fecha'],
            },
        ),
        migrations.CreateModel(
            name='Linea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10)),
                ('pdf_url', models.URLField()),
                ('pdf_filename', models.CharField(max_length=100)),
                ('activa', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='lanchas.empresa')),
            ],
            options={
                'verbose_name': 'línea',
                'verbose_name_plural': 'líneas',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='RecorridoTramo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name': 'tramo de recorrido',
                'verbose_name_plural': 'tramos de recorrido',
                'ordering': ['servicio', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='Via',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=250)),
            ],
            options={
                'verbose_name': 'vía',
                'verbose_name_plural': 'vías',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('tipo', models.CharField(choices=[('troncal', 'Troncal'), ('ramal', 'Ramal'), ('fraccionado', 'Fraccionado'), ('desdoblamiento', 'Desdoblamiento')], max_length=15)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('linea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='lanchas.linea')),
                ('vias', models.ManyToManyField(related_name='servicios', through='lanchas.RecorridoTramo', to='lanchas.via')),
            ],
            options={
                'verbose_name_plural': 'servicios',
                'ordering': ['linea', 'orden', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='recorridotramo',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tramos', to='lanchas.servicio'),
        ),
        migrations.AddField(
            model_name='recorridotramo',
            name='via',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tramos', to='lanchas.via'),
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(choices=[('ida', 'Ida (desde Tigre)'), ('vuelta', 'Vuelta (hacia Tigre)')], max_length=6)),
                ('tipo_dia', models.CharField(choices=[('lunes', 'Lunes'), ('martes', 'Martes'), ('miercoles', 'Miércoles'), ('jueves', 'Jueves'), ('viernes', 'Viernes'), ('sabado', 'Sábado'), ('domingo', 'Domingo'), ('feriado', 'Feriado')], max_length=10)),
                ('hora', models.TimeField()),
                ('condicion', models.CharField(blank=True, help_text='Nota de los PDFs, ej: "los martes y jueves no ingresa a Arroyo Grande"', max_length=300)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='lanchas.servicio')),
            ],
            options={
                'verbose_name_plural': 'horarios',
                'ordering': ['tipo_dia', 'direccion', 'hora'],
            },
        ),
        migrations.CreateModel(
            name='ActualizacionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('pdf_hash', models.CharField(blank=True, max_length=64)),
                ('pdf_modificado', models.BooleanField(default=False)),
                ('exito', models.BooleanField(default=True)),
                ('horarios_agregados', models.IntegerField(default=0)),
                ('horarios_eliminados', models.IntegerField(default=0)),
                ('errores', models.JSONField(default=list)),
                ('notas', models.TextField(blank=True)),
                ('linea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actualizaciones', to='lanchas.linea')),
            ],
            options={
                'verbose_name': 'log de actualización',
                'verbose_name_plural': 'logs de actualización',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddIndex(
            model_name='recorridotramo',
            index=models.Index(fields=['via', 'servicio'], name='lanchas_rec_via_id_d3ae14_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='recorridotramo',
            unique_together={('servicio', 'orden')},
        ),
        migrations.AlterUniqueTogether(
            name='linea',
            unique_together={('empresa', 'numero')},
        ),
        migrations.AddIndex(
            model_name='horario',
            index=models.Index(fields=['tipo_dia', 'hora'], name='lanchas_hor_tipo_di_b6de0e_idx'),
        ),
        migrations.AddIndex(
            model_name='horario',
            index=models.Index(fields=['servicio', 'tipo_dia', 'direccion'], name='lanchas_hor_servici_3e7fc4_idx'),
        ),
    ]
