# Generated by Django 4.2.4 on 2026-07-05 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lanchas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='horario',
            name='destino',
            field=models.ForeignKey(blank=True, help_text='Vía/lugar de destino final de esta fila, solo necesario cuando el servicio se bifurca en más de un destino dentro del mismo IDA o VUELTA (ej: Fraccionado 1 -> Sala 1º Auxilios / Escuela 13).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='horarios_destino', to='lanchas.via'),
        ),
    ]
