# Generated by Django 4.2.4 on 2026-07-06 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lanchas', '0002_horario_destino'),
    ]

    operations = [
        migrations.AddField(
            model_name='linea',
            name='pdf_filename_2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='linea',
            name='pdf_url_2',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='horario',
            name='destino',
            field=models.ForeignKey(blank=True, help_text='Extremo lejano de Tigre de esta fila puntual: lugar de llegada si es ida, lugar de salida si es vuelta. Permite ubicar horarios por un lugar que no es tramo de recorrido (ej. un muelle final), y es imprescindible cuando el servicio se bifurca en más de un destino dentro del mismo IDA o VUELTA (ej: Fraccionado 1 -> Sala 1º Auxilios / Escuela 13).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='horarios_destino', to='lanchas.via'),
        ),
    ]
