# Generated by Django 4.2.4 on 2026-07-07 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lanchas', '0003_linea_pdf_filename_2_linea_pdf_url_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='via',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
